// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RR25xRYeKW3hM_DcBd3skkKOUc6voE0',
    appId: '1:53444492609:web:83eca2d5a10486e20935c0',
    messagingSenderId: '53444492609',
    projectId: 'konstruction-c91a9',
    authDomain: 'konstruction-c91a9.firebaseapp.com',
    storageBucket: 'konstruction-c91a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8RR25xRYeKW3hM_DcBd3skkKOUc6voE0',
    appId: '1:53444492609:android:demo-android-id', // You'll need to add Android app to get real ID
    messagingSenderId: '53444492609',
    projectId: 'konstruction-c91a9',
    storageBucket: 'konstruction-c91a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:1028442672738:ios:demo-app-id',
    messagingSenderId: '1028442672738',
    projectId: 'konstruction-c34e9',
    storageBucket: 'konstruction-c34e9.appspot.com',
    iosBundleId: 'com.konstruction.app.konstructions_tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:1028442672738:ios:demo-app-id',
    messagingSenderId: '1028442672738',
    projectId: 'konstruction-c34e9',
    storageBucket: 'konstruction-c34e9.appspot.com',
    iosBundleId: 'com.konstruction.app.konstructions_tracker',
  );
}
